2.42
htmlacademy-htmlcss/1702959-device-34 pull request #2
Opened 2022-05-30 18:53 UTC by mvn-h24

Скачал картинки, пока смотрел макет, указал ссылки, потому что скачал.

2022-05-31 17:00 UTC, Dima-Dim commented on index.html
> +            <ul class="implicit-list">
Не нужно сюды пытаться всунуть список, не подходит он тут.

2022-05-31 17:01 UTC, Dima-Dim commented on index.html
> +          <li class="features-list__item">Это бесплатно</li>
Ну это уже совсем старнно. Какая цель в списке из одного элемента?

2022-05-31 17:01 UTC, Dima-Dim commented on index.html
> +      <a class="doc-vendor__logo" href="https://htmlacademy.ru/"></a>
https://up.htmlacademy.ru/htmlcss/34/criteries#ALLY-02

2022-06-01 12:51 UTC, mvn-h24 commented on index.html
> +                <strong class="catalog-slider__seo-title">Порхает как бабочка, жалит как пчела!</strong>
Текст кажется чем-то вроде промо-текста, по этому заменил на эмоциональный (em)

2022-06-01 12:51 UTC, mvn-h24 commented on index.html
> +              <img class="catalog-slider__slide" src="images/content/slider-1.png" alt="Квадрокоптер">
Выделил точнее.
Теперь все что связано со сладами выведено в списки, однако возникло пара, как мне кажется лишних контейнеров.
Структуру представляю следущим образом: две колонки, в первой картинки и кнопки, во второй информация разбита по строкам

2022-06-01 12:53 UTC, mvn-h24 commented on catalog.html
> +          <b class="catalog-filter__heading">Фильтр</b>
Испарвил блок фильтра.

2022-06-01 12:53 UTC, mvn-h24 commented on index.html
> +                <label class="pagination-list__point">
Заменил на кнопки.

2022-06-01 12:54 UTC, mvn-h24 commented on index.html
> +        <div class="notify notify__info-message columns-layout__notify">
Убрал, переделал блок (раздел разделил на 3 небольших, в контейнере)

2022-06-01 12:55 UTC, mvn-h24 commented on index.html
> +            <ul class="implicit-list">
Отказался от использования "неявного списка".

2022-06-01 12:56 UTC, mvn-h24 commented on index.html
> +          <li class="features-list__item">Это бесплатно</li>
В макете, это выглядит, как небольшое уведомление, предположил что таких уведомлений может быть несколько и лучше сразу сделать список.

2022-06-01 13:15 UTC, mvn-h24 commented on catalog.html
> +        <menu class="nav-list">
Заменил на ul.

2022-06-29 03:38 UTC, Dima-Dim requested changes

2022-06-29 03:38 UTC, Dima-Dim commented on catalog.html
> +              <b class="catalog-filter__prop-name">Стоимость</b>
Тег b тут использован не по назначению. Стилизацией правильнее и удобнее управлять с помощью CSS. Ранее уже писал об этом.

2022-06-29 03:38 UTC, Dima-Dim commented on index.html
> +            <ol class="catalog-slider__slideshow-layout">
Судя по этой разметке, изображения не являются частью слайдов, но это не так. Слайд состоит в том числе и из изображения.

2022-06-29 03:38 UTC, Dima-Dim commented on index.html
>                <a class="line-btn anchor-btn" href="catalog.html/#product-page">Подробнее</a>
Тоже часть конкретного слайда куда-то выпала.

2022-06-29 03:38 UTC, Dima-Dim commented on index.html
> +              <li class="catalog-slider__slide-addition">
Тоже части слайдов.

2022-07-01 11:58 UTC, merged